heat_template_version: 2017-09-01

description: Template that installs a wordpress server and supporting MySQL database running on separate servers including the dedicated network

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for server. Please use an Ubuntu based image.
    default: Ubuntu 16.04
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used on the compute instance.
    default: m1.small
  public_network:
    type: string
    label: Public network name or ID
    description: Public network to attach server to.
    default: public
  prefix:
    type: string
    label: Name prefix
    description: The prefix to use for the SSH keypair name.

resources:
  key:
    type: https://raw.githubusercontent.com/engel75/HOT/master/wordpress/lib/key.yaml
    properties:
       prefix: { get_param: prefix }

  network:
    type: https://raw.githubusercontent.com/engel75/HOT/master/wordpress/lib/private_network.yaml
    properties:
      public_network: { get_param: public_network }

  mysql:
    type: https://raw.githubusercontent.com/engel75/HOT/master/wordpress/lib/mysql.yaml
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key: { get_attr: [key, name] }
      private_network: { get_attr: [network, name] }
      database_name: wordpress
      database_user: wordpress_user

  wordpress:
    type: https://raw.githubusercontent.com/engel75/HOT/master/wordpress/lib/wordpress.yaml
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key: { get_attr: [key, name] }
      private_network: { get_attr: [network, name] }
      mysql_server: { get_attr: [mysql, ip] }
      database_name: wordpress
      database_user: wordpress_user
      database_password: { get_attr: [mysql, database_password] }
